language: node_js
node_js:
    - "7"
    - "6"
addons:
    code_climate:
        repo_token: d97115774297bc8039645d81ba3ba7aec5171db807e63aeebbdbddb7d7d10ca0
after_script:
    - cat coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js

